<#
.SYNOPSIS
    Turn recorded .ais captures into ais_log.h for playback on the panel.

.DESCRIPTION
    Reads every capture in -Source and emits a single header holding each log
    as a C string literal plus an index table the UI reads to build its file
    selector. The ESP32 maps const arrays straight into flash, so no PROGMEM
    accessor is needed and the same pointer works in the host tests.

    One string literal PER LINE, concatenated: MSVC caps a single literal at
    64 KB, and the captures exceed that. Adjacent-literal concatenation has no
    such limit, so the generated header stays portable to the host toolchain.

    The captures themselves are committed under AIS_Recordings/; the generated
    header is gitignored as a build artifact, since it only duplicates their
    bytes. Re-run this script after adding or changing a recording.

.PARAMETER Source
    Directory of .ais / .txt captures. Default: AIS_Recordings next to the repo root.

.PARAMETER Out
    Output header path. Default: <repo>/ais_log.h

.PARAMETER MaxLines
    Cap lines taken from each capture, to bound flash use. 0 = no cap.

.EXAMPLE
    pwsh tools/make_ais_log.ps1
    pwsh tools/make_ais_log.ps1 -MaxLines 800
#>
[CmdletBinding()]
param(
    [string]$Source,
    [string]$Out,
    [int]$MaxLines = 0
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
if (-not $Source) { $Source = Join-Path $root 'AIS_Recordings' }
if (-not $Out)    { $Out    = Join-Path $root 'ais_log.h' }

if (-not (Test-Path $Source)) { throw "No capture directory at $Source" }

$files = Get-ChildItem $Source -File |
         Where-Object { $_.Extension -in '.ais', '.txt', '.nmea' } |
         Sort-Object Name
if ($files.Count -eq 0) { throw "No .ais/.txt/.nmea captures in $Source" }

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine('/* GENERATED by tools/make_ais_log.ps1 -- do not edit by hand.')
$null = $sb.AppendLine(' *')
$null = $sb.AppendLine(' * Embedded AIS recordings for playback mode. Gitignored on purpose: these')
$null = $sb.AppendLine(' * are real captures and this repository is public. Regenerate with:')
$null = $sb.AppendLine(' *     pwsh tools/make_ais_log.ps1')
$null = $sb.AppendLine(' */')
$null = $sb.AppendLine('#ifndef AIS_LOG_H')
$null = $sb.AppendLine('#define AIS_LOG_H')
$null = $sb.AppendLine('')

$defs = @()
$i = 0
foreach ($f in $files) {
    # Keep only real sentences; a capture can carry blank or commented lines.
    $lines = Get-Content $f.FullName | Where-Object { $_ -match '^\s*[!$]' }
    if ($MaxLines -gt 0 -and $lines.Count -gt $MaxLines) {
        $lines = $lines[0..($MaxLines - 1)]
    }
    if ($lines.Count -eq 0) { Write-Warning "skipping $($f.Name): no sentences"; continue }

    # Display name for the dropdown: base name, de-underscored, kept short.
    # 12 chars: LVGL draws the dropdown chevron OVER the label rather than
    # reserving room for it, and the selector narrowed to 140 px to make room
    # for the speed control beside it.
    $name = $f.BaseName -replace '[_]+', ' '
    if ($name.Length -gt 12) { $name = $name.Substring(0, 12).TrimEnd() }

    $sym = "kAisLog$i"
    $null = $sb.AppendLine("/* $($f.Name): $($lines.Count) sentences */")
    $null = $sb.AppendLine("static const char $sym[] =")
    foreach ($l in $lines) {
        $esc = $l.Trim() -replace '\\', '\\' -replace '"', '\"'
        $null = $sb.AppendLine("  `"$esc\n`"")
    }
    $null = $sb.AppendLine('  ;')
    $null = $sb.AppendLine('')

    $defs += [pscustomobject]@{ Name = $name; Sym = $sym; Count = $lines.Count }
    Write-Host ("  {0,-32} {1,5} sentences" -f $f.Name, $lines.Count) -ForegroundColor Green
    $i++
}

if ($defs.Count -eq 0) { throw 'No usable captures found.' }

$null = $sb.AppendLine('typedef struct {')
$null = $sb.AppendLine('  const char   *name;   /* label for the UI selector */')
$null = $sb.AppendLine('  const char   *data;')
$null = $sb.AppendLine('  unsigned long len;    /* bytes, excluding the NUL */')
$null = $sb.AppendLine('} AisLogDef;')
$null = $sb.AppendLine('')
$null = $sb.AppendLine('static const AisLogDef AIS_LOGS[] = {')
foreach ($d in $defs) {
    $null = $sb.AppendLine("  { `"$($d.Name)`", $($d.Sym), (unsigned long)(sizeof($($d.Sym)) - 1u) },")
}
$null = $sb.AppendLine('};')
$null = $sb.AppendLine("static const int AIS_LOG_COUNT = $($defs.Count);")
$null = $sb.AppendLine('')
$null = $sb.AppendLine('#endif /* AIS_LOG_H */')

# UTF-8 without BOM: the Arduino/GCC toolchain and MSVC both read it cleanly,
# and Set-Content -Encoding utf8 on PS 5.1 would add a BOM.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($Out, $sb.ToString(), $utf8NoBom)

$kb = [math]::Round((Get-Item $Out).Length / 1KB, 1)
Write-Host "==> wrote $Out ($kb KB, $($defs.Count) logs)" -ForegroundColor Cyan
